FROM node:18 AS build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run dev

FROM node:18 AS server-stage

WORKDIR /app

COPY --from=build-stage /app .

RUN npm install -g json-server --legacy-peer-deps

CMD ["json-server", "--watch", "db.json", "--host", "0.0.0.0", "--port", "3000"]
